name: vertexai_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  flutter_chat_ui: ^2.1.1
  flutter_chat_types: ^3.6.2
  flutter_chat_core: ^2.1.1
  image_picker: ^1.1.2
  firebase_ai: ^2.0.0
  path_provider: ^2.1.5
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
